#!/usr/bin/env python3
"""Python port of run_compliance_scan.ps1 (T1585).

g-skl-compliance helper, called by @g-compliance-scan and @g-compliance-gate.

This mirrors the PS1's documented Phase-1 behavior (tracked by the PS1's
TODO[TASK-906] follow-up): detect the scanner name, write a placeholder
compliance report to .gald3r/reports/, print PASS diagnostics, and exit 0.
The full ORT/FOSSA/Snyk/PMD pipeline lands with the TASK-906 follow-up; this
port intentionally does not extend the scan surface beyond the PS1.
"""
# @subsystems: SECURITY_AND_COMPLIANCE
from __future__ import annotations
# --- gald3r calltrace bootstrap (T268) -- injected; inert unless gald3r call tracing is
# enabled. Strip everywhere: python scripts/inject_calltrace_bootstrap.py --strip
import os as _g3ct_os
_g3ct_home = _g3ct_os.environ.get("GALD3R_HOME") or _g3ct_os.path.join(
    _g3ct_os.path.expanduser("~"), ".gald3r")
_g3ct_env = (_g3ct_os.environ.get("GALD3R_TRACE_CALLS") or "").strip().lower()
if _g3ct_env not in ("", "0", "off", "false", "no") or _g3ct_os.path.isfile(
        _g3ct_os.path.join(_g3ct_home, "calltrace.json")):
    try:
        _g3ct_bs = _g3ct_os.path.join(_g3ct_home, "calltrace_bootstrap.py")
        if _g3ct_os.path.isfile(_g3ct_bs):
            with open(_g3ct_bs, "r", encoding="utf-8") as _g3ct_fh:
                exec(compile(_g3ct_fh.read(), _g3ct_bs, "exec"),
                     {"__g3ct_script__": __file__,
                      "__name__": "_gald3r_calltrace_exec"})
    except Exception:
        pass
# --- end gald3r calltrace bootstrap ---

import argparse
import shutil
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional, Sequence


def _bootstrap_engine_utils() -> bool:
    """Make gald3r.utils importable via the installed package.

    T274 (P5-E blocker): the pre-retirement ".gald3r_sys/engine/src" fallback
    walk is removed -- ".gald3r_sys/" is actively purged from every project
    by the deploy pipeline (T335) and never exists in a fresh install, so
    that branch was permanently dead code, not a real fallback.
    """
    try:
        import gald3r.utils  # noqa: F401
        return True
    except ImportError:
        return False


_HAS_UTILS = _bootstrap_engine_utils()

SCANNER_CHOICES = ("auto", "ort", "fossa", "snyk", "pmd", "pmdc", "fallback")


def detect_scanner(requested: str) -> str:
    """Return the requested scanner, or auto-detect the first one on PATH."""
    if requested != "auto":
        print(f"g-skl-compliance: using specified scanner: {requested}")
        return requested
    detected: Optional[str] = None
    for cmd in ("ort", "fossa", "snyk", "pmdc", "pmd"):
        if shutil.which(cmd):
            detected = cmd
            break
    if not detected:
        detected = "fallback"
    print(f"g-skl-compliance: auto-detected scanner: {detected}")
    return detected


def build_report(detected: str, repo_root: str, timestamp: str) -> str:
    """Compose the placeholder compliance report body (same text as the PS1)."""
    return f"""# Compliance Report — {timestamp}

**Scanner**: {detected} (stub — full pipeline not yet implemented)
**Repo root**: {repo_root}
**Verdict**: COMPLIANCE: PASS

## Note

This report was generated by the stub implementation of run_compliance_scan.py.
The full scan pipeline is deferred to a follow-up task.

To perform a real compliance scan, install one of the supported scanners:
- ORT: https://github.com/oss-review-toolkit/ort/releases
- FOSSA: https://github.com/fossas/fossa-cli
- Snyk: npm install -g snyk && snyk auth

## Summary Table

| Package | Version | Declared License | Risk |
|---------|---------|-----------------|------|
| (stub — no packages scanned) | — | — | — |

## Verdict

COMPLIANCE: PASS (stub — no real scan performed)
"""


def build_parser() -> argparse.ArgumentParser:
    """Argparse surface mirroring the PS1 param() block."""
    p = argparse.ArgumentParser(
        description="g-skl-compliance scan helper (placeholder pipeline)."
    )
    p.add_argument("-Scanner", "--scanner", dest="scanner", default="auto",
                   choices=SCANNER_CHOICES,
                   help="Scanner name to use. Default: auto")
    p.add_argument("-RepoRoot", "--repo-root", dest="repo_root",
                   default=str(Path.cwd()),
                   help="Path to repository root. Default: current directory")
    p.add_argument("-Strict", "--strict", dest="strict", action="store_true",
                   help="Reserved: WARN exits with code 1 instead of 0 "
                        "(no WARN paths in the placeholder pipeline).")
    return p


def main(argv: Optional[Sequence[str]] = None) -> int:
    """CLI entry: detect scanner -> validate root -> write report -> PASS."""
    args = build_parser().parse_args(argv)

    detected = detect_scanner(args.scanner)

    repo_root = Path(args.repo_root)
    if not repo_root.exists():
        print(f"ERROR: g-skl-compliance: repo root not found: {args.repo_root}",
              file=sys.stderr)
        return 2

    print(f"g-skl-compliance: repo root = {args.repo_root}")

    reports_dir = repo_root / ".gald3r" / "reports"
    reports_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M UTC")
    date_stamp = datetime.now().strftime("%Y%m%d")
    report_path = reports_dir / f"compliance_{date_stamp}.md"

    report_path.write_text(build_report(detected, args.repo_root, timestamp),
                           encoding="utf-8")
    print(f"g-skl-compliance: report written to {report_path}")
    print("g-skl-compliance: COMPLIANCE: PASS (stub)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
