// gald3r-hooks-plugin.ts -- generated by `gald3r platform install` (T418 / BUG-360, BUG-367).
// Do not hand-edit; re-run the install to regenerate.
//
// OpenCode has no directory-scanned/declarative hook config
// (PLATFORM_SPEC.md section 6): hooks are event-driven JS/TS plugins that
// export one or more functions, each returning an object keyed by native
// event/hook name. This is gald3r's ONE real hook trigger surface for
// OpenCode -- the canonical `g-hk-on-<event>.py` entrypoints under
// `.opencode/plugins/gald3r-hooks/` remain the shared hook core's dispatchers (each
// shells out to `g_hk_core.dispatch(<event>)`, which runs gald3r's full
// per-event concern chain).
//
// Two real OpenCode dispatch mechanisms, not one uniform shape (BUG-367):
// `tool.execute.before`/`tool.execute.after` are real top-level `Hooks`
// interface keys and are registered directly; `session.created`/
// `session.deleted`/`session.idle` are NOT `Hooks` keys at all -- they are
// bus `Event` variants delivered only through the single generic `event`
// hook, discriminated below by `event.type`. Every handler marshals
// OpenCode's REAL argument shape into a `{tool_name, tool_input}` (or
// `{session_id}`) dict `_hook_common.read_stdin_json()` expects, never a
// bare JSON array.
//
// BUG-368: the {tool_name, tool_input} shape above was not enough on its
// own -- OpenCode's real tool ids are lowercase (`edit`/`write`/
// `apply_patch`, live-verified against packages/opencode/src/tool/*.ts's
// Tool.define(...) calls) and its path argument key is camelCase
// (`filePath`), neither of which matched the Claude-Code-shaped
// WRITE_TOOLS/PATH_KEYS vocabulary the tool-start concern chain reads (the
// g-rl-33 .gald3r/ guard, the PRD freeze gate, the workspace-member guard).
// normalizeToolPayload() below renames a known write-tool id to its
// Claude-Code-shaped equivalent and adds a `file_path` key
// alongside the original `filePath` (never removing it) so
// those shared, platform-agnostic Python hooks recognize the call without
// needing any OpenCode-specific vocabulary of their own. Tool ids with no
// entry in WRITE_TOOL_ID_MAP (read, bash, glob, grep, task, ...) pass
// through completely unchanged.
//
// BUG-369 (T424): `apply_patch` has no top-level path argument at all -- its
// sole real parameter is `patchText`, a unified-diff body with per-hunk
// target paths embedded in `*** {Add,Delete,Update} File:` / `*** Move to:`
// header lines (live-verified against packages/opencode/src/patch/index.ts's
// parsePatchHeader()). extractApplyPatchHeaderPaths()/pickApplyPatchPath()
// below mirror that real parser's own `.startsWith(...)`/`.slice(...).trim()`
// convention to pull every recognized header path out of `patchText`,
// surfacing whichever one resolves under `.gald3r/` (or the first path, or a
// broader `.gald3r/`-substring fallback when no header is recognized at all)
// as `file_path` so the same containment check fires for
// apply_patch the way it already does for edit/write.
//
// Native OpenCode event -> gald3r canonical event, per
// `.opencode/plugins/gald3r-hooks/g_hk_core.py`'s PLATFORM_EVENT_MAP["opencode"]
// (ground truth, not invented here):
//   session.created -> g-hk-on-session-start.py (routed via the generic `event` hook)
//   session.deleted -> g-hk-on-session-end.py (routed via the generic `event` hook)
//   tool.execute.before -> g-hk-on-tool-start.py
//   tool.execute.after -> g-hk-on-tool-end.py
//   session.idle -> g-hk-on-stop.py (routed via the generic `event` hook)

import { spawnSync } from "node:child_process";
import * as path from "node:path";

export const Gald3rHooks = async ({ directory }: { directory: string }) => {
  function runHook(scriptName: string, payload: unknown): void {
    try {
      spawnSync("python", [path.join(directory, ".opencode/plugins/gald3r-hooks", scriptName)], {
        input: JSON.stringify(payload ?? {}),
        encoding: "utf-8",
        stdio: ["pipe", "inherit", "inherit"],
        windowsHide: true,
      });
    } catch {
      // gald3r hooks must never crash the host session.
    }
  }

  // BUG-368 (T423): OpenCode-native tool id/arg-key -> Claude-Code-shaped
  // WRITE_TOOLS/PATH_KEYS vocabulary, live-verified against OpenCode's real
  // on-disk tool sources (see the comment block above). Applied once here so
  // the shared Python concern hooks stay platform-agnostic.
  const WRITE_TOOL_ID_MAP: Record<string, string> = { "edit": "Edit", "write": "Write", "apply_patch": "ApplyPatch" };
  const WRITE_TOOL_PATH_KEY = "filePath";
  const CLAUDE_SHAPED_PATH_KEY = "file_path";

  // BUG-369 (T424): apply_patch-specific patch-header path extraction (see
  // the comment block above). Kept separate from the edit/write filePath
  // copy above -- apply_patch has no comparable top-level path field at all.
  const APPLY_PATCH_TOOL_ID = "apply_patch";
  const APPLY_PATCH_TEXT_KEY = "patchText";

  function extractApplyPatchHeaderPaths(patchText: string): string[] {
    // Mirrors packages/opencode/src/patch/index.ts's real parsePatchHeader()
    // line-prefix convention exactly (never a reinvented regex grammar for
    // the header lines themselves) -- only the line-splitting is a regex.
    const headerPrefixes = [
      "*** Add File:",
      "*** Delete File:",
      "*** Update File:",
      "*** Move to:",
    ];
    const paths: string[] = [];
    for (const line of patchText.split(/\r\n|\r|\n/)) {
      for (const prefix of headerPrefixes) {
        if (line.startsWith(prefix)) {
          const candidate = line.slice(prefix.length).trim();
          if (candidate) paths.push(candidate);
          break;
        }
      }
    }
    return paths;
  }

  function pickApplyPatchPath(patchText: unknown): string | undefined {
    if (typeof patchText !== "string") return undefined;
    const headerPaths = extractApplyPatchHeaderPaths(patchText);
    // Multiple hunks may touch multiple files -- the shared containment
    // check only ever inspects a single path field, so a `.gald3r/`-targeting
    // header path always wins over an earlier, non-`.gald3r/` one instead of
    // being silently shadowed by it.
    const gald3rHeaderPath = headerPaths.find((p) => p.includes(".gald3r/"));
    if (gald3rHeaderPath) return gald3rHeaderPath;
    if (headerPaths.length > 0) return headerPaths[0];
    // Fail-safe (BUG-369's own AC): no recognized header line at all -- a
    // malformed/unrecognized patchText must never silently allow a
    // `.gald3r/` target that is literally present somewhere else in the body.
    const fallbackMatch = /([^\s"'`]*\.gald3r\/[^\s"'`]*)/.exec(patchText);
    return fallbackMatch ? fallbackMatch[1] : undefined;
  }

  function normalizeToolPayload(
    toolId: string,
    args: any,
  ): { tool_name: string; tool_input: any } {
    const mapped = WRITE_TOOL_ID_MAP[toolId];
    if (!mapped) {
      return { tool_name: toolId, tool_input: args ?? {} };
    }
    const normalizedInput = { ...(args ?? {}) };
    if (WRITE_TOOL_PATH_KEY in normalizedInput) {
      normalizedInput[CLAUDE_SHAPED_PATH_KEY] = normalizedInput[WRITE_TOOL_PATH_KEY];
    } else if (toolId === APPLY_PATCH_TOOL_ID && APPLY_PATCH_TEXT_KEY in normalizedInput) {
      const patchPath = pickApplyPatchPath(normalizedInput[APPLY_PATCH_TEXT_KEY]);
      if (patchPath !== undefined) {
        normalizedInput[CLAUDE_SHAPED_PATH_KEY] = patchPath;
      }
    }
    return { tool_name: mapped, tool_input: normalizedInput };
  }

  return {
    "tool.execute.before": async (
      input: { tool: string; sessionID: string; callID: string },
      output: { args: any },
    ) => runHook("g-hk-on-tool-start.py", normalizeToolPayload(input.tool, output.args)),

    "tool.execute.after": async (
      input: { tool: string; sessionID: string; callID: string; args: any },
      output: { title: string; output: string; metadata: any },
    ) =>
      runHook("g-hk-on-tool-end.py", {
        ...normalizeToolPayload(input.tool, input.args),
        tool_output: output,
      }),

    // Routes the bus `Event` variants that are NOT real `Hooks` keys
    // (BUG-367) -- see the per-event comment block above.
    event: async ({ event }: { event: { type: string; properties: any } }) => {
      switch (event.type) {
        case "session.created":
          runHook("g-hk-on-session-start.py", { session_id: event.properties?.info?.id });
          return;
        case "session.deleted":
          runHook("g-hk-on-session-end.py", { session_id: event.properties?.info?.id });
          return;
        case "session.idle":
          runHook("g-hk-on-stop.py", { session_id: event.properties?.sessionID });
          return;
        default:
          return;
      }
    },
  };
};
