// gald3r-hooks.ts -- generated by `gald3r platform install` (T414 / BUG-343).
// Do not hand-edit; re-run the install to regenerate.
//
// Pi has no directory-scanned/declarative hook config (PLATFORM_SPEC.md
// section 6): hooks are TypeScript extension event handlers registered via
// `pi.on(eventName, handler)`. This is gald3r's ONE real hook trigger
// surface for Pi -- the canonical `g-hk-on-*.py` scripts under
// `../hooks/` remain the shared hook core's entrypoints; each
// handler below shells one out with the event payload as JSON on stdin,
// matching the `_hook_common.read_stdin_json()` contract every other
// gald3r-supported platform's hook shim already uses.

import { spawnSync } from "node:child_process";
import * as path from "node:path";

const HOOKS_DIR = path.join(__dirname, "../hooks");

function runHook(scriptName: string, payload: unknown): void {
  try {
    spawnSync("python", [path.join(HOOKS_DIR, scriptName)], {
      input: JSON.stringify(payload ?? {}),
      encoding: "utf-8",
      stdio: ["pipe", "inherit", "inherit"],
      windowsHide: true,
    });
  } catch {
    // gald3r hooks must never crash the host session.
  }
}

export default function (pi: any) {
  pi.on("session_start", (event) => runHook("g-hk-on-session-start.py", event));
  pi.on("session_shutdown", (event) => runHook("g-hk-on-session-end.py", event));
  pi.on("tool_call", (event) => runHook("g-hk-on-tool-start.py", event));
  pi.on("tool_result", (event) => runHook("g-hk-on-tool-end.py", event));
}
